import sliceManagement from "./lib/slice_management";

const {
    CaseCreator,
    loadingApiCases,
    ConverterChain,
    snakeCaseToCamelCaseConverter,
    sortByIdConverter,
    defaultLoader,
    getNewLoader,
    getStubLoader,
    getSimpleLoader,
    getOptionalLoader,
    getUpdater,
    getPublisher,
    getDeleter,
    getResourceInteraction,
    stubLoader,
    CustomSlice,
    getTtlPersistTransform,
    PersistSlice,
    PersistSliceManager,
    SliceManager,
} = sliceManagement;

export {
    CaseCreator,
    loadingApiCases,
    ConverterChain,
    snakeCaseToCamelCaseConverter,
    sortByIdConverter,
    defaultLoader,
    getNewLoader,
    getStubLoader,
    getSimpleLoader,
    getOptionalLoader,
    getUpdater,
    getPublisher,
    getDeleter,
    getResourceInteraction,
    stubLoader,
    CustomSlice,
    getTtlPersistTransform,
    PersistSlice,
    PersistSliceManager,
    SliceManager,
};